### ISSUE TITLE
Kararlı sürüme geçiş (v1.0)

### ISSUE THREAD

**Issue by bugra9** [ubuntu-tr/ubuntu-tr.github.io#77]
Yavaş yavaş v1.0 kararlı sürüme geçiş için gerekenleri konuşmaya başlayalım.

**Alt yapı;**
- [x] Yönetim paneli #79
- [ ] Her bir uzantı dizinine uzantı ile ilgili detayları içeren README.md dosyası eklenmesi
- [ ] Alt yapı hakkında oldukça detaylı bir anlatım
- [ ] Tüm anlatımların İngilizce sürümleri
- [ ] Pdf oluşturma işini Pandoc+Latex ile yapmak yerine javascript ile yapalım.
- [ ] Çatıya ait çekirdek dosyaların tek bir dizin altına taşınması
- [ ] Other yapısının silinip author kısmının öne alınması. Yani "collection" oluşturmaya izin verilmesi
- [ ] "Collection" yapıları belirli gruplar altında kategorize olabilecek.  
- [ ] Uzantılar kanca atacakları "collection" yapılarını tek tek belirtmek yerine tamamına ya da belirli grup altındakilerine diyebilecek.
- [ ] "Collection" yapıları kendilerine kanca atan eklentileri reddedebilecek ve kanca atmamış eklentileri kendine bağlayabilecek.
- [ ] Proje adı olan ubuntu-tr.github.io kısmının SudoPortal gibi bir isimle değiştirilmesi.
- [ ] Yazılımla makalelerin birbirinden ayrılması. Yazılımı master dalında tutup, makale ile ilgili dosyaları ayrı bir dalda tutabiliriz.
- [ ] _data dizini altındakileri ilgili uzantıların altına taşıyalım ve _data dizinini silelim. 
- [ ] Eğer pdf daha eklenmediyse, yazı sayfasında pdf bağlantısı görüntülenmesin.
- [ ] Detaylı arama sayfası
- [x] .gitignore dosyası

**Düzenlemeler;**
- [x] Slider'a yeni resim/makalelerin eklenmesi #74 
- [ ] Birkaç duyuru yazısı yazıp duyurular kısmının bu yazılara giden bağlantılarla değiştirilmesi
- [ ] Editör ile markdown yorumlayıcısının uyumunun arttırılması #72 
- [ ] Sendeyaz sayfasının iyileştirilmesi #68 
- [ ] Yazı sayfasında kod kısmının numaralandırılması
- [x] En alt kısma projenin github sayfa bağlantısının eklenmesi
- [ ] Google için gereken ayarların yapılması
- [x] Ubuntu+1 kategorisini kaldıralım. Aslında çok uzun bir süre önce kaldıralım demiştik ama hala kaldırmamışız. :)
- [x] thumb parametresini kaldıralım.
- [x] Forumdan son iletiler kısmı Google'ın ilgili apisini kaldırması nedeniyle bozulmuş. Bunu direk elimizle yazalım.
- [ ] Header ve footer yazı alanı genişliğini içerik ile eşit yapalım.

Aklıma gelenleri yazdım. Buraya yapılması gerekenleri yazalım ve yazılanları tartışalım ki ne yapacağımız ortaya çıksın.

**Comment by bugra9** [comment]
- [ ] Proje adı olan ubuntu-tr.github.io kısmının SudoPortal gibi bir isimle değiştirilmesi.
- [ ] Yazılımla makalelerin birbirinden ayrılması. Yazılımı master dalında tutup, makale ile ilgili dosyaları ayrı bir dalda tutabiliriz.

**Comment by bugra9** [comment]
- [ ] Ubuntu+1 kategorisini kaldıralım. Aslında çok uzun bir süre önce kaldıralım demiştik ama hala kaldırmamışız. :)
- [ ] _data dizini altındakileri ilgili uzantıların altına taşıyalım ve _data dizinini silelim. 
- [ ] Forumdan son iletiler kısmı Google'ın ilgili apisini kaldırması nedeniyle bozulmuş. Bunu direk elimizle yazalım.

**Comment by alquirel** [comment]
Forumdaki son iletiler kısmı ile Google'ın hangi apisi ilişkideydi ki?

**Comment by bugra9** [comment]
Biliyorsundur, farklı alan adları arasında kaynak paylaşımına izin verilmediği veya jsonp biçimi kullanılmadığı sürece (CORS) javascript ile başka siteden veri okuyamıyorsun. Şu an forum alt alan adı, sudo alt alan adına izin veriyor ama bu kısmı yazdığım vakitler böyle bir izin yoktu ve tembellikten dolayı bu durumu aşmak için Google apisi kullanmıştım. Google apisi parametre olarak verilmiş beslemeyi bağlantıdan alıp jsonp biçimine dönüştürüp geri döndürüyordu.  
https://developers.google.com/feed/  
https://github.com/ubuntu-tr/ubuntu-tr.github.io/blob/master/_extension/rssList/index.js

**Comment by alquirel** [comment]
Anladım. 

Aklıma gelmişken listeye bahsettiğim şu foruma koyacağımız "banner" olayını da ekleyelim.
